/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as ReportTypeRouteImport } from './routes/report.$type'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as CompaniesAZLetterRouteImport } from './routes/companies.a-z.$letter'
import { Route as CompaniesCityDistrictRouteImport } from './routes/companies.city.$district'
import { Route as SitemapsCompaniesNDotxmlRouteImport } from './routes/sitemaps/companies.$n[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTypeRoute = ReportTypeRouteImport.update({
  id: '/report/$type',
  path: '/report/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/admin/import',
    path: '/admin/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CompaniesAZLetterRoute = CompaniesAZLetterRouteImport.update({
  id: '/companies/a-z/$letter',
  path: '/companies/a-z/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCityDistrictRoute = CompaniesCityDistrictRouteImport.update({
  id: '/companies/city/$district',
  path: '/companies/city/$district',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsCompaniesNDotxmlRoute =
  SitemapsCompaniesNDotxmlRouteImport.update({
    id: '/sitemaps/companies/$n.xml',
    path: '/sitemaps/companies/$n.xml',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/company/$slug': typeof CompanySlugRoute
  '/report/$type': typeof ReportTypeRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/companies/a-z/$letter': typeof CompaniesAZLetterRoute
  '/companies/city/$district': typeof CompaniesCityDistrictRoute
  '/sitemaps/companies/$n.xml': typeof SitemapsCompaniesNDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/company/$slug': typeof CompanySlugRoute
  '/report/$type': typeof ReportTypeRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/companies/a-z/$letter': typeof CompaniesAZLetterRoute
  '/companies/city/$district': typeof CompaniesCityDistrictRoute
  '/sitemaps/companies/$n.xml': typeof SitemapsCompaniesNDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/company/$slug': typeof CompanySlugRoute
  '/report/$type': typeof ReportTypeRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/companies/a-z/$letter': typeof CompaniesAZLetterRoute
  '/companies/city/$district': typeof CompaniesCityDistrictRoute
  '/sitemaps/companies/$n.xml': typeof SitemapsCompaniesNDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/pricing'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/company/$slug'
    | '/report/$type'
    | '/admin/import'
    | '/companies/a-z/$letter'
    | '/companies/city/$district'
    | '/sitemaps/companies/$n.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/pricing'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/company/$slug'
    | '/report/$type'
    | '/admin/import'
    | '/companies/a-z/$letter'
    | '/companies/city/$district'
    | '/sitemaps/companies/$n.xml'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/pricing'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/company/$slug'
    | '/report/$type'
    | '/_authenticated/admin/import'
    | '/companies/a-z/$letter'
    | '/companies/city/$district'
    | '/sitemaps/companies/$n.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CompanySlugRoute: typeof CompanySlugRoute
  ReportTypeRoute: typeof ReportTypeRoute
  CompaniesAZLetterRoute: typeof CompaniesAZLetterRoute
  CompaniesCityDistrictRoute: typeof CompaniesCityDistrictRoute
  SitemapsCompaniesNDotxmlRoute: typeof SitemapsCompaniesNDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$type': {
      id: '/report/$type'
      path: '/report/$type'
      fullPath: '/report/$type'
      preLoaderRoute: typeof ReportTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/companies/a-z/$letter': {
      id: '/companies/a-z/$letter'
      path: '/companies/a-z/$letter'
      fullPath: '/companies/a-z/$letter'
      preLoaderRoute: typeof CompaniesAZLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/city/$district': {
      id: '/companies/city/$district'
      path: '/companies/city/$district'
      fullPath: '/companies/city/$district'
      preLoaderRoute: typeof CompaniesCityDistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/companies/$n.xml': {
      id: '/sitemaps/companies/$n.xml'
      path: '/sitemaps/companies/$n.xml'
      fullPath: '/sitemaps/companies/$n.xml'
      preLoaderRoute: typeof SitemapsCompaniesNDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CompanySlugRoute: CompanySlugRoute,
  ReportTypeRoute: ReportTypeRoute,
  CompaniesAZLetterRoute: CompaniesAZLetterRoute,
  CompaniesCityDistrictRoute: CompaniesCityDistrictRoute,
  SitemapsCompaniesNDotxmlRoute: SitemapsCompaniesNDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
