/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as CheckoutSessionStatusRouteImport } from './routes/checkout.session-status'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as OrderReferenceRouteImport } from './routes/order.$reference'
import { Route as ReportTypeRouteImport } from './routes/report.$type'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedAdminApi4allRouteImport } from './routes/_authenticated/admin.api4all'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin.usage'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as ApiPublicRevolutWebhookRouteImport } from './routes/api/public/revolut-webhook'
import { Route as CompaniesAZLetterRouteImport } from './routes/companies.a-z.$letter'
import { Route as CompaniesCityDistrictRouteImport } from './routes/companies.city.$district'
import { Route as SitemapsCompaniesNDotxmlRouteImport } from './routes/sitemaps/companies.$n[.]xml'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutSessionStatusRoute = CheckoutSessionStatusRouteImport.update({
  id: '/session-status',
  path: '/session-status',
  getParentRoute: () => CheckoutRoute,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderReferenceRoute = OrderReferenceRouteImport.update({
  id: '/order/$reference',
  path: '/order/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportTypeRoute = ReportTypeRouteImport.update({
  id: '/report/$type',
  path: '/report/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/account/orders',
    path: '/account/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApi4allRoute =
  AuthenticatedAdminApi4allRouteImport.update({
    id: '/api4all',
    path: '/api4all',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImportRoute =
  AuthenticatedAdminImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicRevolutWebhookRoute = ApiPublicRevolutWebhookRouteImport.update({
  id: '/api/public/revolut-webhook',
  path: '/api/public/revolut-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesAZLetterRoute = CompaniesAZLetterRouteImport.update({
  id: '/companies/a-z/$letter',
  path: '/companies/a-z/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCityDistrictRoute = CompaniesCityDistrictRouteImport.update({
  id: '/companies/city/$district',
  path: '/companies/city/$district',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsCompaniesNDotxmlRoute =
  SitemapsCompaniesNDotxmlRouteImport.update({
    id: '/sitemaps/companies/$n.xml',
    path: '/sitemaps/companies/$n.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/certifications': typeof CertificationsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/session-status': typeof CheckoutSessionStatusRoute
  '/company/$slug': typeof CompanySlugRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/report/$type': typeof ReportTypeRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/admin/api4all': typeof AuthenticatedAdminApi4allRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/revolut-webhook': typeof ApiPublicRevolutWebhookRoute
  '/companies/a-z/$letter': typeof CompaniesAZLetterRoute
  '/companies/city/$district': typeof CompaniesCityDistrictRoute
  '/sitemaps/companies/$n.xml': typeof SitemapsCompaniesNDotxmlRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/certifications': typeof CertificationsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/session-status': typeof CheckoutSessionStatusRoute
  '/company/$slug': typeof CompanySlugRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/report/$type': typeof ReportTypeRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/admin/api4all': typeof AuthenticatedAdminApi4allRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/revolut-webhook': typeof ApiPublicRevolutWebhookRoute
  '/companies/a-z/$letter': typeof CompaniesAZLetterRoute
  '/companies/city/$district': typeof CompaniesCityDistrictRoute
  '/sitemaps/companies/$n.xml': typeof SitemapsCompaniesNDotxmlRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/certifications': typeof CertificationsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/session-status': typeof CheckoutSessionStatusRoute
  '/company/$slug': typeof CompanySlugRoute
  '/order/$reference': typeof OrderReferenceRoute
  '/report/$type': typeof ReportTypeRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/admin/api4all': typeof AuthenticatedAdminApi4allRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/revolut-webhook': typeof ApiPublicRevolutWebhookRoute
  '/companies/a-z/$letter': typeof CompaniesAZLetterRoute
  '/companies/city/$district': typeof CompaniesCityDistrictRoute
  '/sitemaps/companies/$n.xml': typeof SitemapsCompaniesNDotxmlRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/certifications'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/checkout/return'
    | '/checkout/session-status'
    | '/company/$slug'
    | '/order/$reference'
    | '/report/$type'
    | '/account/orders'
    | '/admin/api4all'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/usage'
    | '/admin/users'
    | '/api/public/revolut-webhook'
    | '/companies/a-z/$letter'
    | '/companies/city/$district'
    | '/sitemaps/companies/$n.xml'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/certifications'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/checkout/return'
    | '/checkout/session-status'
    | '/company/$slug'
    | '/order/$reference'
    | '/report/$type'
    | '/account/orders'
    | '/admin/api4all'
    | '/admin/import'
    | '/admin/orders'
    | '/admin/usage'
    | '/admin/users'
    | '/api/public/revolut-webhook'
    | '/companies/a-z/$letter'
    | '/companies/city/$district'
    | '/sitemaps/companies/$n.xml'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/certifications'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/checkout/return'
    | '/checkout/session-status'
    | '/company/$slug'
    | '/order/$reference'
    | '/report/$type'
    | '/_authenticated/account/orders'
    | '/_authenticated/admin/api4all'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/usage'
    | '/_authenticated/admin/users'
    | '/api/public/revolut-webhook'
    | '/companies/a-z/$letter'
    | '/companies/city/$district'
    | '/sitemaps/companies/$n.xml'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CertificationsRoute: typeof CertificationsRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CompanySlugRoute: typeof CompanySlugRoute
  OrderReferenceRoute: typeof OrderReferenceRoute
  ReportTypeRoute: typeof ReportTypeRoute
  ApiPublicRevolutWebhookRoute: typeof ApiPublicRevolutWebhookRoute
  CompaniesAZLetterRoute: typeof CompaniesAZLetterRoute
  CompaniesCityDistrictRoute: typeof CompaniesCityDistrictRoute
  SitemapsCompaniesNDotxmlRoute: typeof SitemapsCompaniesNDotxmlRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/session-status': {
      id: '/checkout/session-status'
      path: '/session-status'
      fullPath: '/checkout/session-status'
      preLoaderRoute: typeof CheckoutSessionStatusRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$reference': {
      id: '/order/$reference'
      path: '/order/$reference'
      fullPath: '/order/$reference'
      preLoaderRoute: typeof OrderReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$type': {
      id: '/report/$type'
      path: '/report/$type'
      fullPath: '/report/$type'
      preLoaderRoute: typeof ReportTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/api4all': {
      id: '/_authenticated/admin/api4all'
      path: '/api4all'
      fullPath: '/admin/api4all'
      preLoaderRoute: typeof AuthenticatedAdminApi4allRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/revolut-webhook': {
      id: '/api/public/revolut-webhook'
      path: '/api/public/revolut-webhook'
      fullPath: '/api/public/revolut-webhook'
      preLoaderRoute: typeof ApiPublicRevolutWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/a-z/$letter': {
      id: '/companies/a-z/$letter'
      path: '/companies/a-z/$letter'
      fullPath: '/companies/a-z/$letter'
      preLoaderRoute: typeof CompaniesAZLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/city/$district': {
      id: '/companies/city/$district'
      path: '/companies/city/$district'
      fullPath: '/companies/city/$district'
      preLoaderRoute: typeof CompaniesCityDistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/companies/$n.xml': {
      id: '/sitemaps/companies/$n.xml'
      path: '/sitemaps/companies/$n.xml'
      fullPath: '/sitemaps/companies/$n.xml'
      preLoaderRoute: typeof SitemapsCompaniesNDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminApi4allRoute: typeof AuthenticatedAdminApi4allRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminApi4allRoute: AuthenticatedAdminApi4allRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CheckoutSessionStatusRoute: typeof CheckoutSessionStatusRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
  CheckoutSessionStatusRoute: CheckoutSessionStatusRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CertificationsRoute: CertificationsRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CompanySlugRoute: CompanySlugRoute,
  OrderReferenceRoute: OrderReferenceRoute,
  ReportTypeRoute: ReportTypeRoute,
  ApiPublicRevolutWebhookRoute: ApiPublicRevolutWebhookRoute,
  CompaniesAZLetterRoute: CompaniesAZLetterRoute,
  CompaniesCityDistrictRoute: CompaniesCityDistrictRoute,
  SitemapsCompaniesNDotxmlRoute: SitemapsCompaniesNDotxmlRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
