/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CompanySlugRouteImport } from './routes/company.$slug'
import { Route as SitemapsCompaniesNDotxmlRouteImport } from './routes/sitemaps/companies-$n[.]xml'
import { Route as CompaniesAZLetterRouteImport } from './routes/companies.a-z.$letter'
import { Route as CompaniesCityDistrictRouteImport } from './routes/companies.city.$district'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanySlugRoute = CompanySlugRouteImport.update({
  id: '/company/$slug',
  path: '/company/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapsCompaniesNDotxmlRoute =
  SitemapsCompaniesNDotxmlRouteImport.update({
    id: '/sitemaps/companies-$n.xml',
    path: '/sitemaps/companies-$n.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompaniesAZLetterRoute = CompaniesAZLetterRouteImport.update({
  id: '/companies/a-z/$letter',
  path: '/companies/a-z/$letter',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCityDistrictRoute = CompaniesCityDistrictRouteImport.update({
  id: '/companies/city/$district',
  path: '/companies/city/$district',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/company/$slug': typeof CompanySlugRoute
  '/sitemaps/companies-$n.xml': typeof SitemapsCompaniesNDotxmlRoute
  '/companies/a-z/$letter': typeof CompaniesAZLetterRoute
  '/companies/city/$district': typeof CompaniesCityDistrictRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/company/$slug': typeof CompanySlugRoute
  '/sitemaps/companies-$n.xml': typeof SitemapsCompaniesNDotxmlRoute
  '/companies/a-z/$letter': typeof CompaniesAZLetterRoute
  '/companies/city/$district': typeof CompaniesCityDistrictRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/company/$slug': typeof CompanySlugRoute
  '/sitemaps/companies-$n.xml': typeof SitemapsCompaniesNDotxmlRoute
  '/companies/a-z/$letter': typeof CompaniesAZLetterRoute
  '/companies/city/$district': typeof CompaniesCityDistrictRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/company/$slug'
    | '/sitemaps/companies-$n.xml'
    | '/companies/a-z/$letter'
    | '/companies/city/$district'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/company/$slug'
    | '/sitemaps/companies-$n.xml'
    | '/companies/a-z/$letter'
    | '/companies/city/$district'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/company/$slug'
    | '/sitemaps/companies-$n.xml'
    | '/companies/a-z/$letter'
    | '/companies/city/$district'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CompanySlugRoute: typeof CompanySlugRoute
  SitemapsCompaniesNDotxmlRoute: typeof SitemapsCompaniesNDotxmlRoute
  CompaniesAZLetterRoute: typeof CompaniesAZLetterRoute
  CompaniesCityDistrictRoute: typeof CompaniesCityDistrictRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/$slug': {
      id: '/company/$slug'
      path: '/company/$slug'
      fullPath: '/company/$slug'
      preLoaderRoute: typeof CompanySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemaps/companies-$n.xml': {
      id: '/sitemaps/companies-$n.xml'
      path: '/sitemaps/companies-$n.xml'
      fullPath: '/sitemaps/companies-$n.xml'
      preLoaderRoute: typeof SitemapsCompaniesNDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/a-z/$letter': {
      id: '/companies/a-z/$letter'
      path: '/companies/a-z/$letter'
      fullPath: '/companies/a-z/$letter'
      preLoaderRoute: typeof CompaniesAZLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/city/$district': {
      id: '/companies/city/$district'
      path: '/companies/city/$district'
      fullPath: '/companies/city/$district'
      preLoaderRoute: typeof CompaniesCityDistrictRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CompanySlugRoute: CompanySlugRoute,
  SitemapsCompaniesNDotxmlRoute: SitemapsCompaniesNDotxmlRoute,
  CompaniesAZLetterRoute: CompaniesAZLetterRoute,
  CompaniesCityDistrictRoute: CompaniesCityDistrictRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
